[package]
name = "galerians-autosplitter"
version = "0.5.0"
authors = ["descawed <github@descawed.com>"]
edition = "2024"
description = "A LiveSplit-compatible autosplitter for speedrunning Galerians in supported emulators"
readme = "README.md"
repository = "https://github.com/descawed/galerians-autosplitter"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.45", features = ["derive"] }
colog = "1.3.0"
log = "0.4.27"
memmap2 = "0.9.7"
nix = { version = "0.30.1", features = ["process", "signal"] }
num-traits = "0.2.19"